【Hackathon 5th No.87】Add edict part
PaddlePaddle/PaddleMIX pull request #307
Opened 2023-11-17 07:48 UTC by co63oc

https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_5th/%E3%80%90PaddlePaddle%20Hackathon%205th%E3%80%91%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E4%B8%AA%E4%BA%BA%E6%8C%91%E6%88%98%E8%B5%9B%E5%A5%97%E4%BB%B6%E5%BC%80%E5%8F%91%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#no87paddlemix-ppdiffusers%E6%96%B0%E5%A2%9Ehf-community%E5%BA%94%E7%94%A8pipeline

参考 edict_pipeline.py https://github.com/huggingface/diffusers/blob/main/examples/community/edict_pipeline.py 基于 ppdiffusers https://github.com/PaddlePaddle/PaddleMIX/tree/develop/ppdiffusers/examples/community 下的 pipeline 实现

fp16不存在，取消设置revision="fp16"
https://bj.bcebos.com/paddlenlp/models/community/CompVis/stable-diffusion-v1-4/fp16/model_index.json

原图
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/2913ef2b-7192-4e08-8d7a-4e397fec0cd8)
生成图
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/9cacc784-3be0-4d91-ba1f-e049bd2ec0ad)

2023-11-17 08:38 UTC, co63oc commented
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/3356cf90-fe9b-4651-ad05-12875463b9fc)
失败CI 为 tests/pipelines/stable_diffusion/test_stable_diffusion_paradigms.py

2023-11-24 05:32 UTC, CrazyBoyM requested changes
你好,
这里需要改为从paddlenlp中加载，代码如下：
```
from paddlenlp.transformers import CLIPTextModel, CLIPTokenizer
```

2023-11-24 05:32 UTC, CrazyBoyM commented on ppdiffusers/examples/community/pipeline_fabric.py
> +from transformers import CLIPTextModel, CLIPTokenizer
from paddlenlp.transformers import CLIPTextModel, CLIPTokenizer

2023-11-24 06:11 UTC, co63oc commented
> 你好, 这里需要改为从paddlenlp中加载，代码如下：
> 
> ```
> from paddlenlp.transformers import CLIPTextModel, CLIPTokenizer
> ```

已修改

2023-11-24 06:37 UTC, westfish commented
你好，请新建一个ppdiffusers/tests/community/，并将测试文件放到该文件夹下

2023-11-24 06:50 UTC, co63oc commented
> 你好，请新建一个ppdiffusers/tests/community/，并将测试文件放到该文件夹下

已修改，现在使用当前目录文件custom_pipeline="edict_pipeline.py"，移动目录后使用edict_pipeline，远程仓库现在没有合并，可能会有找不到文件错误

2023-11-29 13:02 UTC, shiyutang commented
@westfish @CrazyBoyM @JunnYu 请辛苦看是否还有修改需要开发者执行。

2023-11-30 02:39 UTC, JunnYu commented on ppdiffusers/examples/community/pipeline_fabric.py
> +# Copyright 2023 FABRIC authors and the HuggingFace Team. All rights reserved.
Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.

2023-11-30 02:39 UTC, JunnYu commented on ppdiffusers/examples/community/edict_pipeline.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
这下面看看要不要加一下hf那里的copyright

2023-11-30 02:49 UTC, co63oc commented on ppdiffusers/examples/community/pipeline_fabric.py
> +# Copyright 2023 FABRIC authors and the HuggingFace Team. All rights reserved.
已修改

2023-11-30 03:50 UTC, JunnYu commented
最后的话，https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/community/README.md 这里面可以加一下有关这个新pipeline的介绍

2023-11-30 04:19 UTC, co63oc commented
> 最后的话，https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/community/README.md 这里面可以加一下有关这个新pipeline的介绍

已增加pipeline @JunnYu

2023-12-01 04:22 UTC, JunnYu approved these changes
LGTM

2023-12-01 04:22 UTC, merged

2023-12-01 05:56 UTC, guoshengCS commented
也想请问下，看于edict生成结果中相较于输入图片在颜色上有一个整体的偏移，这个对所有图片都有这样的情况吗。看原始repo给的case好像没这个情况，这个是否可能是diffusers中实现存在一些问题 https://github.com/salesforce/EDICT ，这个请问下了解不

2023-12-01 07:06 UTC, co63oc commented
> 也想请问下，看于edict生成结果中相较于输入图片在颜色上有一个整体的偏移，这个对所有图片都有这样的情况吗。看原始repo给的case好像没这个情况，这个是否可能是diffusers中实现存在一些问题 https://github.com/salesforce/EDICT ，这个请问下了解不

不了解，torch测试运行也是同样，https://github.com/salesforce/EDICT 这里如果测试不同那再对比查找是不是有修改

查看代码0.3.0版本，比较不同是float转为double类型
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/eb06626d-79aa-477b-ac92-4505b54516ec)