Update ppdiffusers prior
PaddlePaddle/PaddleMIX pull request #317
Opened 2023-11-23 01:50 UTC by co63oc

https://github.com/PaddlePaddle/PaddleMIX/issues/265

Update ppdiffusers prior

增加scale参数

test_models_prior.py测试
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/865d053f-b432-461d-9cdc-ce8d5b199725)

test_layers_utils.py测试，不通过的为固定值测试，测试换设备后固定值不同
![image](https://github.com/PaddlePaddle/PaddleMIX/assets/4617245/bf93f5c3-07bb-48f8-830c-211e224f7011)

2023-11-24 07:04 UTC, CrazyBoyM requested changes
同学你好，感谢参与开源社区贡献！查看代码发现这里的scale似乎还没有被用上。
参考：https://github.com/huggingface/diffusers/compare/v0.19.3...v0.21.1#diff-a89e72c24a390f4a4d50044cd7651a48b7e313411fa747bb430b1cf5e389bbf9R227

2023-11-24 07:15 UTC, CrazyBoyM commented
> 同学你好，感谢参与开源社区贡献！查看代码发现这里的scale似乎还没有被用上。 参考：[huggingface/diffusers@v0.19.3...v0.21.1#diff-a89e72c24a390f4a4d50044cd7651a48b7e313411fa747bb430b1cf5e389bbf9R227](https://github.com/huggingface/diffusers/compare/v0.19.3...v0.21.1#diff-a89e72c24a390f4a4d50044cd7651a48b7e313411fa747bb430b1cf5e389bbf9R227)

可以在其中点击“files”的tab，搜索models/lora.py，查看该文件从v0.19.3->v0.21.1升级前后的代码变动

2023-11-24 07:32 UTC, co63oc commented
这里修改prior模块，修改lora.py是有依赖，lora.py的其他修改再提PR修改

2023-11-26 04:38 UTC, co63oc commented
合并到 https://github.com/PaddlePaddle/PaddleMIX/pull/322

2023-11-26 04:39 UTC, closed without merging