【PPMix No.02】add test_llava and test_qwen2vl
PaddlePaddle/PaddleMIX pull request #925
Opened 2024-12-25 16:27 UTC by mikemikimike

2024-12-26 02:05 UTC, luyao-cv approved these changes

2024-12-26 05:41 UTC, luyao-cv requested changes
还需要修改

2025-01-07 05:10 UTC, mikemikimike commented
#953  太久没更新，请求更换pr

2025-01-07 06:02 UTC, nemonameless approved these changes

2025-01-07 06:02 UTC, luyao-cv approved these changes

2025-01-08 02:44 UTC, merged